apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixed-app
  labels:
    app: mixed-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixed-app
  template:
    metadata:
      labels:
        app: mixed-app
    spec:
      containers:
      - name: mixed-app
        image: nginx:1.19
        ports:
        - containerPort: 80
